import "./globals.css";
import Newsidebar from "./components/NewSidebar"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative">
        <div className="flex relative">
          
          <div className="flex relative">
            <Newsidebar/>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
